version: '3.8'
services:
  academic-engine:
    image: ghcr.io/jessielch/scholarship-system-platform/academic-engine:latest
    container_name: scholarship_academic_engine
    restart: unless-stopped
    environment:
      - USE_REDIS=true
      - REDIS_URL=redis://10.2.11.111:6379
      - DB_HOST=10.2.11.111
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123!
      - DB_NAME=academicdb
      - RABBITMQ_URL=amqp://admin:admin123@10.2.11.165:5672/
      - PORT=8081
    ports:
      - "8081:8081"

  document-service:
    image: ghcr.io/jessielch/scholarship-system-platform/document-service:latest
    container_name: scholarship_document_service
    restart: unless-stopped
    environment:
      - PORT=8084
      - MONGO_URI=mongodb://admin:admin@10.2.11.111:27017/documents?authSource=admin
      - S3_BUCKET_NAME=uce-distribuida-qa-documents-851725350325
      - AES_SECRET_KEY=secret
      - AWS_ACCESS_KEY_ID=mock
      - AWS_SECRET_ACCESS_KEY=mock
      - AWS_SESSION_TOKEN=mock
      - AWS_REGION=us-east-1
      - SPRING_RABBITMQ_HOST=10.2.11.165
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin123
    ports:
      - "8084:8084"

  workflow-saga:
    image: ghcr.io/jessielch/scholarship-system-platform/workflow-saga:latest
    container_name: scholarship_workflow_saga
    restart: unless-stopped
    environment:
      - REDIS_HOST=10.2.11.111
      - REDIS_PORT=6379
      - KAFKA_BROKERS=10.2.11.165:9092
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
