version: '3.8'
services:
  academic-engine:
    image: ghcr.io/jessielch/scholarship-system-platform/academic-engine:latest
    container_name: scholarship_academic_engine
    restart: unless-stopped
    environment:
      - USE_REDIS=true
      - REDIS_URL=redis://${DATABASE_PRIVATE_IP}:6379
      - PORT=8081
    ports:
      - "8081:8081"

  document-service:
    image: ghcr.io/jessielch/scholarship-system-platform/document-service:latest
    container_name: scholarship_document_service
    restart: unless-stopped
    environment:
      - PORT=8084
      - MONGO_URI=mongodb://admin:admin@${DATABASE_PRIVATE_IP}:27017/documents?authSource=admin
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-uce-distribuida-documents}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
      - SPRING_RABBITMQ_HOST=${DATABASE_PRIVATE_IP}
    ports:
      - "8084:8084"
