version: '3.8'
services:
  api-gateway:
    image: ghcr.io/jessielch/scholarship-system-platform/api-gateway:latest
    container_name: scholarship-gateway
    restart: unless-stopped
    environment:
      - PORT=3000
      - REDIS_URL=redis://${DATABASE_PRIVATE_IP:-redis}:6379
      - IDENTITY_SERVICE_URL=http://${SECURITY_PRIVATE_IP:-scholarship-identity}:3001
      - ACADEMIC_SERVICE_URL=http://${CORE_PRIVATE_IP:-scholarship-academic-engine}:8081
      - DOCUMENT_SERVICE_URL=http://${COMPUTE_PRIVATE_IP:-scholarship-document-service}:8084
      - SAGA_SERVICE_URL=http://${COMPUTE_PRIVATE_IP:-scholarship-workflow-saga}:8083
      - SOCIOECONOMIC_SERVICE_URL=http://${COMPUTE_PRIVATE_IP:-scholarship-socioeconomic}:8082
      - FINANCIAL_SERVICE_URL=http://${CORE_PRIVATE_IP:-scholarship-payment-service}:3003
      - JWT_SECRET=${JWT_SECRET}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./keys:/app/keys

  student-portal:
    image: ghcr.io/jessielch/scholarship-system-platform/student-portal:latest
    container_name: scholarship-student_portal
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://scholarship-gateway:3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    ports:
      - "80:3000"
