version: '3.8'
services:
  identity-service:
    image: ghcr.io/jessielch/scholarship-system-platform/identity-service:latest
    container_name: scholarship-identity
    restart: unless-stopped
    environment:
      - PORT=3001
      - DB_HOST=${DATABASE_PRIVATE_IP:-postgres}
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=identitydb
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./keys:/app/keys
