sonar.projectKey=JessielCH_scholarship-system-platform
sonar.projectName=Scholarship System Platform
sonar.organization=jessielch
sonar.host.url=https://sonarcloud.io
sonar.token=be65645c4c76b0d546f3d4ac4df20f52318e97a3
sonar.branch.name=main
sonar.sourceEncoding=UTF-8

# Definimos las fuentes de código de absolutamente todo nuestro monorepo (10,000+ líneas)
sonar.sources=apps

# Excluir únicamente carpetas generadas por compilación (dist, build, target, node_modules) y ejecutables binarios
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.next/**,**/*.exe

# Evaluamos la cobertura de todas las aplicaciones del monorepo sin exclusiones ni atajos (9,000+ líneas)
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/tests/**,**/test/**

# Rutas exactas y oficiales de reportes de cobertura para todos los lenguajes (TypeScript, JavaScript, Java, Go)
sonar.javascript.lcov.reportPaths=apps/payment-service/coverage/lcov.info,apps/identity-service/coverage/lcov.info,apps/api-gateway/coverage/lcov.info
sonar.typescript.lcov.reportPaths=apps/payment-service/coverage/lcov.info,apps/identity-service/coverage/lcov.info,apps/api-gateway/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=apps/document-service/target/site/jacoco/jacoco.xml,apps/workflow-saga/target/site/jacoco/jacoco.xml
sonar.go.coverage.reportPaths=apps/academic-engine/coverage.out
