sonar.projectKey=uce-scholarship-system-platform
sonar.projectName=Scholarship System Platform
sonar.sourceEncoding=UTF-8

# Excluimos de la revisión de código los tests y carpetas compiladas
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/dist/**,**/build/**

# Propiedad requerida por SonarQube si hay archivos Java (evita que el scan falle si no están compilados)
sonar.java.binaries=.
